cloudflare:
    token: ENC[AES256_GCM,data:bYOkQAU2lpx1Rg1Fj2ph9OHEVxbdLzXsHJkTxZJXEpsDrFaqfk6H1tJe6VVNujhAzBVVjJI=,iv:zUI0xGmtHDMr969QyStLtu1UUS3X8onREjrZWvM7Cgs=,tag:Ro4bMI7McIaezlvKeURuhg==,type:str]
wireless:
    unit_221-psk: ENC[AES256_GCM,data:5ixLDaxL4vJMvLVaXbGxDIYDVBVCeXvfELXyNEw3RV+K6EcoUCPiZSQ6OaBsrMudmE39dSD7oOE7bWbbeCaRSg==,iv:1tPSSsjXD2Vd9bbuZBdDKkS5QgNZPNnb4Yss1UvcPEU=,tag:b66YbynSR8sw8s5cE5tTWA==,type:str]
noah:
    password: ENC[AES256_GCM,data:e/IgO72RvmXTtGM9u7z8X4k3WMHNllGwaNJNl1WaEa6prblVh6VG4Qw/sDaWm1HBffTqc5ptRb9YGMPko1EjQz9bBIgeq+7h7A==,iv:apMqg9+od6Ue5x7dE0FLKWkqXLEnWxxuK5WtCjj4PZU=,tag:795acBNqK2No5SL5omE6+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUHBkRTdWQzMwV0tCVkdr
            SlR5SUFUQVY5VTFkWnB2NlJUQ25zOFRpK204CmlDRjNpNGFzTG5JZUpmQVNwMWlP
            UHVJa0t0d08wQUZoTmZWdjBoY3I5NjgKLS0tIEdBOEozYklHa2pVa1o0eWtNYitk
            ZzY3Q2FOTHZKZEZMTGlIek1vbi9KNzgK9nc9NhLlg4GhhyS2WnT2+4OUjigdHdWx
            6g10g4fKwpI/ehMYB7nB2o8vIBzO4nAH86/FEPzauKjSldZmjlmffQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12cgfdr7rxcr4555fwr4sg38cu6n97unpk66gkt9n5ts47reamgdq6vguy2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNzJyNzVaZ3BOOXUyUWFB
            enZnbnl2aC9sTVFvQ3I1OFFGMUcvZGRmMXd3CmlCdlkzUXFCeGF6WjBITlJhOTIr
            Qlk3OGk5V1J6NGdEMTR4V1YzR3hPQjgKLS0tIFhXUWVVMEx0cEJqNXZuRllMR0JW
            TlMycDlwV1Mzc1dKYTZnMXhkOVRVVjAKiEN3c25pT/OOb7gbFpcNLXDQFrsTL/p6
            zeElttdrGae5RigUBCzTcQMy73ORYhD3hpDSgFlaXy7ppf7KzlwNZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17fjjnpf9pe3gqy8n65cy6mv2fpyxm92wm9d9q0sc9k2z43ulqfqqdznhrf
    lastmodified: "2026-09-05T14:36:19Z"
    mac: ENC[AES256_GCM,data:28acLCWaWD5BJqdQ5XU4CPfPqDHOoNdutYpLPU4qYY5sq3+2xX98YrBuoSMRuPQKzL0qmd7xskJUnUMdPAhy3cfCJPzxFjbwjfN+sS7OwPy/GGXQ+gpOY9yv3BdDwmD7FDh0Q2CGmEtHxxq772179qn58ig2b9VVRTJn0YG6CyQ=,iv:gxjEIPUxIoMZ29FG9GqECirHoiLZnJJ2ZwAjHfAt6Os=,tag:twjp+RHD/DQYzfPH/IgL+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
