cloudflare:
    token: ENC[AES256_GCM,data:bYOkQAU2lpx1Rg1Fj2ph9OHEVxbdLzXsHJkTxZJXEpsDrFaqfk6H1tJe6VVNujhAzBVVjJI=,iv:zUI0xGmtHDMr969QyStLtu1UUS3X8onREjrZWvM7Cgs=,tag:Ro4bMI7McIaezlvKeURuhg==,type:str]
wireless:
    unit_221-psk: ENC[AES256_GCM,data:5ixLDaxL4vJMvLVaXbGxDIYDVBVCeXvfELXyNEw3RV+K6EcoUCPiZSQ6OaBsrMudmE39dSD7oOE7bWbbeCaRSg==,iv:1tPSSsjXD2Vd9bbuZBdDKkS5QgNZPNnb4Yss1UvcPEU=,tag:b66YbynSR8sw8s5cE5tTWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S01TZkZtZEF0ZmNuY0F6
            SGFIUDhmNTJNb2Q3a0JaL2VsV2xjWG9Sa2xvCk1jN0ZwTWl2STRFZHN4QlRCc1hp
            SExNV1JCRDAyMzgrNG1YWFFCMFE2YkEKLS0tIERMdDZ4OVQxa1A4T0kzUE4rY0Mr
            M3orT2RxWGxXMStjUStKQzV4NFB3M2MKnKYmNhnD0Hj0M5ABe5aosasLipBl9BQQ
            4ZKM4owqe1H4V6jCxmq0vPvecPxOVz9gzdMe/GboIIsdlIU9JrWwZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12cgfdr7rxcr4555fwr4sg38cu6n97unpk66gkt9n5ts47reamgdq6vguy2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTG0wRmhvVWNUWXFPV3Yv
            bXgrLytLN2kwVldhRTErbzN6ellqQ1A2NXk0CkVra1hOT29lYlNiRjJtUnRLMjl1
            aVhEUkt2Tk01SlZvWGVMb0IwcWpsS1kKLS0tIHBTcStPRE5hZHpKaXFRbFR1WVUv
            T1NVTWk0TEtacVF0NCtUbzI4YkJ4dzAKvYv/7XeMJOxlv8eythIR8ePXidaCDQHE
            1hgUqfVgGTWxeIJkffAwcG4PrQAY2reTWXaY2XewuLzYJipHXC5zog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age193qzfrwa5lxztdtag5ypfgd46jwtc5k603qmm5d8av4pgcgcjv4qhjznnk
    lastmodified: "2026-09-05T14:36:19Z"
    mac: ENC[AES256_GCM,data:28acLCWaWD5BJqdQ5XU4CPfPqDHOoNdutYpLPU4qYY5sq3+2xX98YrBuoSMRuPQKzL0qmd7xskJUnUMdPAhy3cfCJPzxFjbwjfN+sS7OwPy/GGXQ+gpOY9yv3BdDwmD7FDh0Q2CGmEtHxxq772179qn58ig2b9VVRTJn0YG6CyQ=,iv:gxjEIPUxIoMZ29FG9GqECirHoiLZnJJ2ZwAjHfAt6Os=,tag:twjp+RHD/DQYzfPH/IgL+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
